version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    

  express-app:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3000:3000"

 
# docker-compose up



